@startuml UI

title <size:30><b>Simplified Dependencies of IG_mkGraph_any_ins_all_nodes</b></size>


skinparam linetype ortho


package "IG_mkGraph_theory" {
    rectangle IG_mkGraph_any_ins_all_nodes

    rectangle _insEdges_does_not_add_nodes
    rectangle _insEdge_does_not_add_node

    rectangle _insNodes_any_ins_all_nodes

    rectangle _insNode_any_ins_node
}

package "IG_theory" {
    rectangle IG_and_adds_node

    rectangle IG_match_removes_node
    rectangle IG_match_exactly_removes_node

    rectangle "_updAdj_addSucc_[...]"
    rectangle "_updAdj_addPred_[...]"
    rectangle "_updAdj_clearSucc_[...]"
    rectangle "_updAdj_clearPred_[...]"

    rectangle _updAdj_sameLabel_f_does_not_change_IG_labNodes
    rectangle _updateEntry_sameLabel_f_does_not_change_IG_labNodes

}

package "IG_wf" {
    rectangle IG_match_returns_node
}

IG_mkGraph_any_ins_all_nodes --> _insEdges_does_not_add_nodes
IG_mkGraph_any_ins_all_nodes --> _insNodes_any_ins_all_nodes

_insEdges_does_not_add_nodes --> _insEdge_does_not_add_node
_insEdge_does_not_add_node --> IG_and_adds_node
_insEdge_does_not_add_node --> IG_match_removes_node
_insEdge_does_not_add_node --> IG_match_exactly_removes_node
_insEdge_does_not_add_node --> IG_match_returns_node

_insNodes_any_ins_all_nodes --> _insNode_any_ins_node

_insNode_any_ins_node --> IG_and_adds_node


IG_and_adds_node --> "_updAdj_addSucc_[...]"
IG_and_adds_node --> "_updAdj_addPred_[...]"

IG_match_removes_node --> "_updAdj_clearPred_[...]"
IG_match_removes_node --> "_updAdj_clearSucc_[...]"

IG_match_exactly_removes_node --> "_updAdj_clearPred_[...]"
IG_match_exactly_removes_node --> "_updAdj_clearSucc_[...]"


"_updAdj_addPred_[...]" --> _updAdj_sameLabel_f_does_not_change_IG_labNodes
"_updAdj_addSucc_[...]" --> _updAdj_sameLabel_f_does_not_change_IG_labNodes

"_updAdj_clearSucc_[...]" --> _updAdj_sameLabel_f_does_not_change_IG_labNodes
"_updAdj_clearPred_[...]" --> _updAdj_sameLabel_f_does_not_change_IG_labNodes


_updAdj_sameLabel_f_does_not_change_IG_labNodes --> _updateEntry_sameLabel_f_does_not_change_IG_labNodes


@enduml
